export {
  detectPathType,
  resolveTranslationPaths,
  autoDiscoverTranslations,
  resolveTranslationsConfig,
  deepMerge,
  loadCache,
  saveCache,
  isCacheValid,
  toRelativeImport,
  toGlobPattern,
  getNamespaceFromPath,
  wrapWithNamespace,
  generateNamespaceWrapperCode,
  type PathType,
} from './translations';
